### ISSUE TITLE
/akn FRBR URI prefix

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/cobalt#17]
AKN 3 requires that AKN FRBR URIs start with `/akn/`. Non-AKN FRBR URIs must start with some other prefix.

I think Cobalt will need to support both the old style (`/xx[-locality]/`) and new-style (`/akn/`), at least for a short while.

## Proposal

1. Cobalt must be able to parse FRBR URIs that start with `/akn/`
2. Cobalt should assume that FRBR URIs that don't start with `/akn/` but do match the `/xx[-locality]/` initial format are valid, un-prefixed FRBR URIs. ie. be backwards-compatible with what we do today.
3. Cobalt should throw an error for prefixed FRBR URIs that it doesn't understand (eg. `/ukpga/...`).
3. When turning a parsed FRBR URI into a string, it should by default include the `/akn/` prefix. We should be able to disable this, perhaps by setting `frbr_uri.prefix = None`.

These will have to be guided by our use cases.

**Comment by goose-life** [comment]
closed by #21
