### ISSUE TITLE
strftime does not allow dates prior to 1900

### ISSUE THREAD

**Issue by rkunal** [laws-africa/cobalt#3]
https://github.com/Code4SA/cobalt/blob/26afd41d2e3ee9f950c14fa3ee06a1d19d7c5e30/cobalt/act.py#L23

In the above code, for Unicode strings, function strftime() throws error on dates prior to 1900.

https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior

> The exact range of years for which strftime() works also varies across platforms. Regardless of platform, years before 1900 cannot be used.

I am using Python 2.7.6 , Ubuntu 14.04

**Comment by longhotsummer** [comment]
Good point. We can replace that line with the following one, does that help?

```
return "%04d-%02d-%02d" % (value.year, value.month, value.day)
```

Have you found any other places where this occurs?

**Comment by rkunal** [comment]
Thanks @longhotsummer . I did not find this in any other place. 
Really appreciate the prompt response.

Requesting for a pull . #4

**Comment by rkunal** [comment]
With this pull request, should I make changes to release a new version too ?
