### ISSUE TITLE
As a developer I want to import documents in the most recent version of AKN

### ISSUE THREAD

**Issue by Gauntlet173** [laws-africa/cobalt#57]
http://docs.oasis-open.org/legaldocml/ns/akn/3.0/WD17 is not a recognized namespace.

**Comment by longhotsummer** [comment]
I don't believe that is an official namespace. That's the namespace from the working draft specification in 2016. According to http://docs.oasis-open.org/legaldocml/akn-core/v1.0/akn-core-v1.0-part1-vocabulary.html from 2018, the official namespace is  http://docs.oasis-open.org/legaldocml/ns/akn/3.0

**Comment by longhotsummer** [comment]
If you really need support for this namespace, you can add it to the list of namespaces that cobalt uses when parsing:

```python
from cobalt.akn import AKN_NAMESPACES
AKN_NAMESPACES['WD17'] = 'http://docs.oasis-open.org/legaldocml/ns/akn/3.0/WD17'
```

**Comment by Gauntlet173** [comment]
Sounds good. Any idea why it's the namespace used in some of the official examples?

**Comment by longhotsummer** [comment]
Probably because those examples were developed while the standard was still a draft, and they haven't gone back to clean them up.
